#!/bin/bash
array=(5 6 4  5)

sum=0


#for element in "${array[@]}"
#do
#  sum=$((sum + element))
#done
#echo "the sum of array is : ${sum}"
lenght=${#array[@]}

for (( i=4 ; i=>$lenght ; i++));do
	sum=${array[@]}
done
echo "${sum}"
